// A version of helpers.js that lets webpack figure 
// out what to require (ie doesn't have any dynamic logic mixed in w/ require statements).

// Export full list of helpers
module.exports = [
    require('./helpers/all'),
    require('./helpers/any'),
    require('./helpers/assignVar'),
    require('./helpers/block'),
    require('./helpers/cdn'),
    require('./helpers/compare'),
    require('./helpers/concat'),
    require('./helpers/contains'),
    require('./helpers/decrementVar'),
    require('./helpers/dynamicComponent'),
    require('./helpers/encodeHtmlEntities'),
    require('./helpers/for'),
    require('./helpers/getContentImage'),
    require('./helpers/getContentImageSrcset'),
    require('./helpers/getFontLoaderConfig'),
    require('./helpers/getFontsCollection'),
    require('./helpers/getImage'),
    require('./helpers/getImageManagerImage'),
    require('./helpers/getImageManagerImageSrcset'),
    require('./helpers/getImageSrcset'),
    require('./helpers/getImageSrcset1x2x'),
    require('./helpers/getVar'),
    require('./helpers/helperMissing'),
    require('./helpers/if'),
    require('./helpers/incrementVar'),
    require('./helpers/inject'),
    require('./helpers/join'),
    require('./helpers/jsContext'),
    require('./helpers/json'),
    require('./helpers/lang'),
    require('./helpers/langJson'),
    require('./helpers/limit'),
    require('./helpers/money'),
    require('./helpers/nl2br'),
    require('./helpers/occurrences'),
    require('./helpers/or'),
    require('./helpers/partial'),
    require('./helpers/pluck'),
    require('./helpers/pre'),
    require('./helpers/region'),
    require('./helpers/replace'),
    require('./helpers/resourceHints'),
    require('./helpers/setURLQueryParam'),
    require('./helpers/snippets'),
    require('./helpers/stripQuerystring'),
    require('./helpers/strReplace'),
    require('./helpers/stylesheet'),
    require('./helpers/thirdParty'),
    require('./helpers/toLowerCase'),
    require('./helpers/truncate'),
    require('./helpers/unless'),
];
